language: generic

jobs:
  include:
    - stage: circa10a
      name: awk
      script: time ./circa10a/breadsticks.sh word_number.txt
    - stage: cujarrett
      name: node
      script: time node ./cujarrett/index.js word_number.txt
    # TODO Go
    # - script: go ...
    #   name: "Go"
    - stage: Torpus
      language: rust
      script:
        - cd Torpus/breadsticks &&
          cargo build --verbose --release &&
          time target/release/breadsticks ../../word_number.txt
